<!DOCTYPE html>
<html lang="en">
    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link href="/components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
        <link href="/css/style.css" rel="stylesheet">

        <script src="/components/jquery/dist/jquery.min.js"></script>
        <script src="/components/bootstrap/dist/js/bootstrap.min.js"></script>


        <title>Minimal Zend Framework</title>
    </head>
    <body>

        <div class="container">

            <div class="row">
                <div class="col-md-12 margin-top">
                </div>

            </div>

            <?php echo $this->content; ?>

        </div>
    </body>
</html>
