<!DOCTYPE html>
<html lang="en">
    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link href="/components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">

        <?php if ($this->configurationHelper()['environment'] == 'production') { ?>
            <link href="/css/style.min.css" rel="stylesheet">
        <?php } else { ?>
            <link href="/css/style.css" rel="stylesheet">
        <?php } ?>

        <script src="/components/jquery/jquery.min.js"></script>
        <script src="/components/bootstrap/dist/js/bootstrap.min.js"></script>


        <title>Orinoco River Zend Framework demo site</title>
    </head>
    <body>

        <div class="container">

            <div class="header"> 

                <nav class="navbar navbar-inverse" role="navigation">
                    <div class="container">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                        </div>

                        <div class="collapse navbar-collapse">
                            <ul class="nav navbar-nav">

                                <?php $req = $this->requestUriHelper(); ?>

                                <li <?php echo ((isset($req) && $req == '/') ? "class='active'" : ""); ?> ><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>

                                <?php if (!$this->zfcUserIdentity()): ?>
                                    <li <?php echo ((isset($req) && $req == '/do/login') ? "class='active'" : ""); ?>><a href="<?php echo $this->url('custom-login-page') ?>"><?php echo $this->translate('Login') ?></a></li>
                                    <?php endIf; ?>

                                <?php if ($this->zfcUserIdentity()): ?>
                                    <li <?php echo ((isset($req) && $req == '/user/logout') ? "class='active'" : ""); ?>><a href="<?php echo $this->url('zfcuser/logout') ?>"><?php echo $this->translate('Logout') ?></a></li>
                                    <?php endIf; ?>

                                <?php if ($this->zfcUserIdentity()): ?>
                                    <li <?php echo ((isset($req) && $req == '/account') ? "class='active'" : ""); ?>><a href="<?php echo $this->url('account') ?>"><?php echo $this->translate('Account') ?></a></li>
                                    <?php endIf; ?>

                            </ul>
                        </div><!--/.nav-collapse -->

                </nav>

            </div>

            <div class="content">

                <?php echo $this->flashHelper()->render(); ?>

                <?php echo $this->content; ?>

            </div>

        </div>

        <div class="footer">

            <p>&copy; Orinoco River ZF2 Project <?php echo date('Y'); ?></p>


        </div>

    </div>
</body>
</html>
