<div class="row">
    <div class="col-md-8">
	<h1><?php echo sprintf($this->translate('Change Email for %s'), $this->zfcUserDisplayName()); ?></h1>
	<?php if ($status === true) : ?>
	<div class="alert alert-success"><?php echo $this->translate('Email address changed successfully.'); ?></div>
	<?php elseif ($status === false) : ?>
    	<div class="alert alert-error"><?php echo $this->translate('Unable to update your email address. Please try again.'); ?></div>
	<?php endif; ?>
	<?php
	$form = $this->changeEmailForm;

	$form->prepare();
	$form->setAttribute('action', $this->url('changeemail'));
	$form->setAttribute('method', 'post');
	$form->setAttribute('class', "form-horizontal");
	?>
	<?php echo $this->form()->openTag($form) ?>

	<?php foreach ($form as $element): ?>
	    <?php $element->setAttribute('class', 'form-control'); ?>
	    <?php $element->setOptions(array('label_attributes' => array('class' => 'control-label col-md-4'))); ?>
    	<div class="form-group">
		<?php if ($element->getLabel() != null): ?>
		    <?php echo $this->formLabel($element) ?>
		<?php endif ?>
		<?php if ($element instanceof Zend\Form\Element\Button): ?>
		    <?php echo $this->formButton($element) ?>
		<?php elseif ($element instanceof Zend\Form\Element\Captcha): ?>
		    <?php echo $this->formCaptcha($element) . $this->formElementErrors($element) ?>
		<?php else: ?>
			    <div class="col-md-8">  <?php echo $this->formInput($element) . $this->formElementErrors($element) ?> </div>
		<?php endif ?>
    	</div>	    
	<?php endforeach ?>

	<?php if ($this->redirect): ?>
    	<input type="hidden" name="redirect" value="<?php echo $this->redirect ?>" />
	<?php endif ?>
	<input type="submit" class="btn btn-default" value="Submit" />
	<?php echo $this->form()->closeTag() ?>

    </div>
</div>
