<div class="row">

    <div class="col-md-8">

        <h1><?php echo sprintf($this->translate('Change Password for %s'), $this->zfcUserDisplayName()); ?></h1>

        <?php if ($status === true) : ?>
        <div class="alert alert-success"><?php echo $this->translate('Password changed successfully.'); ?></div>
        <?php elseif ($status === false) : ?>
            <div class="alert alert-error"><?php echo $this->translate('Unable to update your password. Please try again.'); ?></div>
        <?php endif; ?>

            <?php
            $form = $this->changePasswordForm;

            $form->setAttribute('class', "form-horizontal");
            $form->get('credential')->setAttribute('class', 'form-control');
            $form->get('newCredential')->setAttribute('class', 'form-control');
            $form->get('newCredentialVerify')->setAttribute('class', 'form-control');
            $form->get('submit')->setAttribute('class', 'btn btn-default');


            $form->get('credential')->setOptions(array('label_attributes' => array('class' => 'control-label col-md-6')));
            $form->get('newCredential')->setOptions(array('label_attributes' => array('class' => 'control-label col-md-6')));
            $form->get('newCredentialVerify')->setOptions(array('label_attributes' => array('class' => 'control-label col-md-6')));

            $form->prepare();
            $form->setAttribute('action', $this->url('changepassword'));
            $form->setAttribute('method', 'post');

            $emailElement = $form->get('identity');
            $emailElement->setValue($this->zfcUserIdentity()->getEmail());

            echo $this->form()->openTag($form);
            ?>

            <?php echo $this->formElementErrors($form->get('identity')); ?>
            <?php echo $this->formInput($form->get('identity')); ?>

            <div class="form-group">	  
                <?php echo $this->formLabel($form->get('credential')); ?>
                <div class="col-md-4">
                    <?php echo $this->formInput($form->get('credential')) . $this->formElementErrors($form->get('credential')); ?>


            </div>
        </div>

            <div class="form-group">	   
                <?php echo $this->formLabel($form->get('newCredential')); ?>
                <div class="col-md-4">
                    <?php echo $this->formInput($form->get('newCredential')) . $this->formElementErrors($form->get('newCredential')); ?>
                </div>
            </div>

            <div class="form-group">	   
                <?php echo $this->formLabel($form->get('newCredentialVerify')); ?>
                <div class="col-md-4">
                    <?php echo $this->formInput($form->get('newCredentialVerify')) . $this->formElementErrors($form->get('newCredential')); ?>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-4">
                    <?php echo $this->formInput($form->get('submit')); ?>
                </div>
            </div>
            <?php echo $this->form()->closeTag(); ?>

    </div>

</div>
